api/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import *
from rest_framework import routers
from api.views import ProductViewSet


router = routers.DefaultRouter()
router.register(r'products', ProductViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

authorization/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import *

app_name = 'authorization'

urlpatterns = [
    path('login/', login_view, name='login_view'),
    path('register/', register_view, name='register_view'),
    path('logout/', logout_view, name='logout_view'),

]

mta/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('authorization/', include('authorization.urls')),
    path('panel/', include('panel.urls')),
    path('api/v1/', include('api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import *


urlpatterns = [
    path('', index, name='index'),
    # path('products/<str:category>/', loadProducts, name='load_products_by_category'),
]

api/models.py
from django.db import models

# Create your models here.

authorization/models.py
# models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.username
    

panel/models.py
from django.db import models

book_category = (
    ("E", "E-book"),
    ("H", "Hardcover"),
    ("P", "Paperback")
)


class Product(models.Model):
    title = models.CharField(max_length=50)
    manufacturer = models.CharField(max_length=50)
    image = models.ImageField(upload_to="products")
    description = models.TextField(max_length=255)
    category = models.CharField(choices=book_category,
                                default="E-book", max_length=50, verbose_name="Category")

    @staticmethod
    def get_all_products():
        return Product.objects.all()

    @staticmethod
    def delete_product(pk: int):
        Product.objects.get(pk=pk).delete()

    def update_book(self):
        pass

authorization/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2')

panel/forms.py
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'manufacturer', 'image', 'description', 'category']

api/views.py
from django.shortcuts import render, HttpResponse
from rest_framework import viewsets, serializers
from panel.models import Product


class ProductSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Product
        fields = ['id', 'title', 'description', 'manufacturer', 'image', 'category']



class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

authorization/views.py
# views.py
from django.contrib.auth import login, authenticate, logout
from django.db import IntegrityError
from .forms import CustomUserCreationForm 
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import logging


logger = logging.getLogger(__name__)


def register_view(request):
    error_message = None

    if request.user.is_authenticated:
            logger.error(f"user {request.user} is already logged in")

            return redirect('/')
    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            try:
                form.save()

                user = form.instance
                login(request, user)

                logger.error(f"user {user} registered and logged in")

                return redirect('/panel/')  
            except IntegrityError:
                error_message = "Login already exists. Choose a different login."
        else:
            print(form.errors)
            error_message = "Invalid form. Please check the input values."
    
    return render(request, 'authorization/register.html', {'error_message': error_message})


def login_view(request):
    if request.user.is_authenticated:
            logger.error(f"user {request.user} is already logged in")

            return redirect('/')
    
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            logger.error(f"user {user} logged in")

            return redirect('/panel/')
        else:
            return render(request, 'authorization/login.html', {'error_message': 'Invalid login or password'})
        
    return render(request, 'authorization/login.html')


@login_required(login_url='/authorization/login/')
def logout_view(request):
    user = request.user
    logout(request)

    logger.error(f"User {user} logged out")

    return redirect('/')

shop/views.py
from urllib import response
from django.http import HttpResponse
from django.shortcuts import render
from panel.models import Product


import logging
logger = logging.getLogger(__name__)


def index(request):
    products = Product.objects.all()

    return render(request, 'shop/index.html', {'products': list(products)})

authorization/templates/authorization/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
     
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <title>login</title>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    
    <form method="post" action="{% url 'authorization:login_view' %}">
        {% csrf_token %}
        
            <a href="{% url 'index' %}" class="previous round">&#8249;</a>
            <h3>Login Here</h3>
        

        <label for="username">Username</label>
        <input type="text" name="username" placeholder="username">
    
        <label for="password">Password</label>
        <input type="password" name="password" id="password" placeholder="password">
    
        <button type="submit">Log In</button>
    
    
        <div class="error_msg">
            {% if error_message %}
                {{ error_message }}
            {% endif %}
        </div>
    </form>

    <!-- <section>
        <a href="{% url 'authorization:register_view' %}">Register if u dont have an account xd</a>
    </section>
    <section>
        <a href="{% url 'index' %}">Go to shop</a>
    </section> -->
</body>
</html>

authorization/templates/authorization/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
     
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <title>login</title>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    
    <form method="post" action="{% url 'authorization:register_view' %}">
        {% csrf_token %}
        
            <a href="{% url 'index' %}" class="previous round">&#8249;</a>
            <h3>Register Here</h3>
        

        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Username">
    
        <label for="password1">Password</label>
        <input type="password" name="password1" id="password1" placeholder="Password">

        <label for="password2">Confirm password</label>
        <input type="password" name="password2" id="password2" placeholder="Confirm password">
    
        <button type="submit">Register</button>
    
    
        <div class="error_msg">
            {% if error_message %}
                {{ error_message }}
            {% endif %}
        </div>
    </form>

    <!-- <section>
        <a href="{% url 'authorization:register_view' %}">Register if u dont have an account xd</a>
    </section>
    <section>
        <a href="{% url 'index' %}">Go to shop</a>
    </section> -->
</body>
</html>

shop/templates/shop/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>Document</title>
  </head>

  <div class="advertisement modal accept">
      <p class="timer"></p>
      <a class="modal-action-button">X</a>

    <div class="main-content">
        <h1>Тут могла б бути корисна реклама</h1>
        <p>Всього дві хвилини на день...</p>
    </div> 
</div>

<div class="book-modal modal">
    <a class="modal-action-button">X</a>
   <div class="main-content">
      <h1>Назва</h1>
      <p>Опис</p>
  </div> 
</div>

  <div class="accept modal">
      <div class="main-content">
          <h1>Підпишіться на повідомлення від нас</h1> 
      </div>
      
    <div class="accept-button">
      <button class="book_button acceptButton">Accept</button>
      <button class="book_button acceptButton">Decline</button>
    </div>
  </div>
  <body>
    <header class="main-header">
      <h1>📘 The Best Book Store.</h1>

      <nav>
        <a href="#">Магазин</a>
        <a href="#">Акції</a>
        <a href="#">Программа лояльності</a>
        <a href="#">Повернення</a>
        <a href="#">Про нас</a>
      </nav>
    </header>

    <header class="poster">
      <div class="poster-text">
        <h2>The world belongs to those who read.</h2>
        <p>Rick Holland</p>
      </div>
      <img src="{% static 'media/default/book-poster.svg' %}" alt="" srcset="" />
    </header>

    <header class="shop">
      <div class="filters">
        <a id='all' class="a-clicked filter">Всі</a>
        <a id="e-book" class="filter">Електронні</a>
        <a id="paperback" class="filter">Паперові</a>
        <a id="hardcover" class="filter">Тврерда палітурка</a>
      </div>

      <div class="products"></div>
    </header>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="{% static 'js/push_advertisement.js' %}"></script>
    <script src="{% static 'js/products_worker.js' %}"></script>
    <script src="{% static 'js/subscription.js' %}"></script>
    <script src="{% static 'js/product_info.js' %}"></script>
     >
  
{#    <script src="data/comics.js"></script>#}
{#    <script src="assets/js/index.js"></script>#}
  </body>
</html>